#!/usr/bin/env python3

import argparse
parser = argparse.ArgumentParser()
parser.add_argument(dest='dice_rolls', nargs='*')
args = parser.parse_args()

dictionary = vars(args)
print(f"{dictionary}")

rolls = dictionary['dice_rolls']
print(f"{rolls}")
